index.html

Hi, while discovering the ONNX website I discovered that some links are broken because of missing href attribute values.
This PR fixes the broken links.

fixes github and getting-started links

---

getting-started.html

fix broken pytorch export link

---

getting-started.html

Ahh, no more repo changes before I have coffee.. :)

Mis-titled the installation link

---

getting-started.html

Updating info on repo details, documentation, and tutorial for export.

Update getting-started with info on MXNet

---

partials/hamburger-menu.html
partials/nav.html

Remove getting started page, since it's redundant and not kept up to date.

Add link to the model zoo

---

index.html

a open format -> an open format

---

supported-tools.html

https://github.com/onnx/onnx/issues/2382

Fix TVM link

---

sc_apply.html

The html points directly to Google form which will collect candidate information for ONNX Steering Committee election.

Create a shortcut link to SC application form

---

js/news.json

Update news for release 1.7 with the same release message
provided to LF AI.

Update news for release 1.7

---

js/news.json

Add ONNX slack channel to news

Update ONNX slack news

---

js/news.json

Update news for release 1.8 with the same release message

Update news for release 1.8

---

js/news.json

Signed-off-by: Sheng Zha <zhasheng@amazon.com>
@prasanthpul

add March 2021 meetup news

---

index.html
partials/navigation.html

Signed-off-by: Prasanth Pulavarthi <prasanth.pulavarthi@microsoft.com>

Replace Gitter link with Slack for "Chat With Us"

---

js/news.json

Added news item for roadmap, pointing to our roadmap slack channel

News item for roadmap 2021-2022

---

js/news.json

Signed-off-by: Rajeev Rao <rajeevrao@nvidia.com>

News dispatch for onnx v1.10.0 release

---

supported-tools.html

keras-onnx is not longer actively developed
https://github.com/onnx/keras-onnx#keras2onnx

Update Keras link to go to tf2onnx

---

css/custom.css
supported-tools.html

Add text links below icons that do not themselves have readable text.

Add text below icons

---

js/news.json

Added the roadmap info, with all of the detailed topics in the google doc linked in the READ MORE link

Added roadmap updates to news ticker

---

js/news.json

Added the announcement for Oct meetup, copying and updating the version used for the last meetup in spring 2021.

Added meetup oct 21, 2021

---

js/news.json

Signed-off-by: Liqun Fu <liqfu@microsoft.com>

add onnx 1.11.0 release news

---

js/news.json

update for the election dates

---

election-guide.html
index.html
sc-candidates.html
supported-tools.html

Signed-off-by: Andreas Fehlner <fehlner@arcor.de>

change link to github repos from 'master' to 'main'

---

js/news.json

Signed-off-by: Liqun Fu <liqfu@microsoft.com>

add onnx 1.12.0 release news

---

js/news.json
meetups/june2022.html

Preview: https://faxu.github.io/onnx.github.io/

Update ONNX Community Day page

---

css/custom.css
partials/footer.html
partials/navigation.html

Currently I am still bothered by the distance between the arrow and the separator. (I want to check how to remove the separator or increase the spacing).
I am not sure how to structure the navbar best.
I think this still needs to be discussed: 
* I can imagine different entry points for the different target groups.
* Additionally the different repos under the roof of the Onnx
Signed-off-by: andife <fehlner@arcor.de>

extended navbar

---

partials/navigation.html

connected to https://github.com/onnx/onnx/pull/4623

Update links to match new doc URLs

---

js/news.json

Added news item with link to steering committee roadmap landing page

added news item for roadmap 2022-2023

---

js/news.json

try to fix reason why news vanished

---

js/news.json

Signed-off-by: p-wysocki <przemyslaw.wysocki@intel.com>

Add news for ONNX 1.13 release

---

supported-tools.html

Two updates are in this PR:
Replace ONNX converter from transformers to optimum(the converter has been migrated to the Optimum library)
Update the URL of Optimum to the documentation
Thanks!

Update support tools from Hugging Face

---

js/news.json

v1.14.0 release news

---

.github/workflows/main.yml

This PR address issue #187. I have added a GitHub action to check for json linting using the [json-lint](https://github.com/marketplace/actions/json-lint) action from the GibHub marketplace. This workflow is triggered on `push` and `pull_request`. Do let me know if any changes are required.

Json lint workflow

---

js/news.json

ONNX 1.16.0 release news

---

supported-tools.html

The previous PR #99 was added to the wrong section on the webpage
Signed-off-by: Zhipeng Huang <zhipengh512@gmail.com>

Relocate code for Ascend logo to Inference section

---

js/news.json

Release news update for ONNX v1.17.0

ONNX v1.17.0 release update

---

js/news.json

add relevant news item with link to Microsoft form that enables candidates to self nominate

Update news for SC 2025-2026 candidates

---

js/news.json

added list of candidates to steering committee for year 2025 in news feed.

added news about candidate list
